### ISSUE TITLE
simulate magnetic neutron pattern from a .mcif file

### ISSUE THREAD

**Issue by dragonyanglong** [AdvancedPhotonSource/GSAS-II#121]
Dear @briantoby , In the GUI, GSAS-II can read a .mcif file, and simulate the magnetic and nuclear neutron diffraction pattern successfully. Is it possible to do the same job in python using GSASIIscriptable? Thanks!

**Comment by dragonyanglong** [comment]
Right now, I mimic the magnetic pattern simulation as the following, not sure if it is correct?

```
import GSASIIscriptable as G2sc

gpx = G2sc.G2Project(newgpx='mcif_sim.gpx') # create a project
phase0 = gpx.add_phase("1.31_MnO.mcif", phasename="MnO",mag=True)
hist1 = gpx.add_simulated_powder_histogram("MCIF simulation", "RT_BANK2.instprm"),Tmin=1,Tmax=30,Tstep=0.001, phases=gpx.phases(), ibank=2)
```

**Comment by dragonyanglong** [comment]
In addition, how to convert neutron TOF to d or Q unit?

**Comment by briantoby** [comment]
I don't believe magnetic computations have ever been tested from scripting. Please check the GUI computation against the scripted one and if they don't agree, please reopen this, but please supply a script & .gpx to duplicate the bug. 

The G2PwdrData.Export() might offer a file that has d or Q in it. Otherwise, you can call GSASIIlattice.Pos2dsp() to compute that yourself. There are some examples for calling that inside GSASIIscriptable.

**Comment by dragonyanglong** [comment]
Thanks! Comparing my experimental neutron data, the magnetic simulation function seems to be correct.

For converting the TOF to d spacing, can you give some clues, I didn't find the example. I tried the following but shows error. (I attach the gpx file but added .txt extension)

```
import GSASIIscriptable as G2sc
from GSASIIlattice import TOF2dsp

inst = gpx.histogram(0).data['Instrument Parameters'][0]
pos = gpx.histogram(0).data['data']
d_value = TOF2dsp(inst, pos)
```



```
    dsp0 = Pos/Inst['difC'][1]
           ~~~^~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'list' and 'float'
[gsas_sim.gpx.txt](https://github.com/user-attachments/files/18217128/gsas_sim.gpx.txt)

```

**Comment by briantoby** [comment]
I had intended that you look at the source code in GSASIIscriptable to see how GSASIIlattice.Pos2dsp() is used, but it was easy enough to add a new option to G2PwdrData.getdata to transform to X values to Q & d-space. I did not test the new code, so I'd appreciate you checking that it works properly.

**Comment by dragonyanglong** [comment]
Thanks. I tried the `Pos2dsp()` using your newly added code as an example, and it works great for calculating d and Q!

For testing the `G2PwdrData.getdata`, it seems like my GUI version has been updated to the newest version including your new commit. But the GSASIIscriptable doesn't seem to be the newest version, and it shows the errors as follows. So I couldn't test the `G2PwdrData.getdata` yet.

```
(gsas2) longyang@192 Desktop % python mcif_simulate.py
======================================================================
Module pyspg in '/Users/longyang/opt/anaconda3/envs/gsas2/GSASII/bindist' could not be loaded
error msg: dlopen(/Users/longyang/opt/anaconda3/envs/gsas2/GSASII/bindist/pyspg.cpython-311-darwin.so, 0x0002): Library not loaded: /usr/local/gfortran/lib/libgfortran.5.dylib
  Referenced from: <658599DE-9A48-3BD0-91BE-DBC2671C2750> /Users/longyang/opt/anaconda3/envs/gsas2/GSASII/bindist/pyspg.cpython-311-darwin.so
  Reason: tried: '/usr/local/gfortran/lib/libgfortran.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/gfortran/lib/libgfortran.5.dylib' (no such file), '/usr/local/gfortran/lib/libgfortran.5.dylib' (no such file), '/usr/local/lib/libgfortran.5.dylib' (no such file), '/usr/lib/libgfortran.5.dylib' (no such file, not in dyld cache)
======================================================================
GSAS-II binary directory: /Users/longyang/opt/anaconda3/envs/gsas2/GSASII-bin/mac_64_p3.11_n1.26
7 values read from config file /Users/longyang/opt/anaconda3/envs/gsas2/GSASII/config.py
/Users/longyang/Documents/Tongji/cifs/mcif/1.31_MnO.mcif read by Reader CIF
gpx file saved as /Users/longyang/Desktop/gsas_sim.gpx
Simulating 3402 points from 1 to 30 millisec
Instrument parameters read: /Users/longyang/Documents/Tongji/beamtime/CSNS/20240618MPI/data/YangLong20240618/temp/RT_Instrum/RT_BANK2.instprm (G2 fmt) bank 2
gpx file saved as /Users/longyang/Desktop/gsas_sim.gpx
 Hessian Levenberg-Marquardt SVD refinement on 1 variables:
initial chi^2 4.854e+06 with 3401 obs.
Read from file:/Users/longyang/Desktop/gsas_sim.bak0.gpx
Save to file  :/Users/longyang/Desktop/gsas_sim.gpx
GPX file save successful
 Refinement results are in file: /Users/longyang/Desktop/gsas_sim.lst
 ***** Refinement successful *****
gpx file saved as /Users/longyang/Desktop/gsas_sim.gpx
Traceback (most recent call last):
  File "/Users/longyang/Desktop/mcif_simulate.py", line 160, in <module>
    sim_neutron(cif_fn="/Users/longyang/Documents/Tongji/cifs/mcif/1.31_MnO.mcif", save_fn="result", calc_type = 'both', units='d', bank=2)
  File "/Users/longyang/Desktop/mcif_simulate.py", line 57, in sim_neutron
    x_dd = gpx.histogram(0).getdata('d')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/longyang/opt/anaconda3/envs/gsas2/GSASII/GSASIIscriptable.py", line 3562, in getdata
    raise G2ScriptException("Invalid datatype = "+datatype+" must be one of "+str(enums))
GSASIIscriptable.G2ScriptException: Invalid datatype = d must be one of ['x', 'yobs', 'yweight', 'ycalc', 'background', 'residual']
```


GUI version:
```
  Python:     3.11.10  from /Users/longyang/opt/anaconda3/envs/GSASII/GSAS-II/GSAS-II.app/Contents/MacOS/GSAS-II. 
  wx:         4.2.1  
  matplotlib: 3.9.2  
  numpy:      1.26.4  
  scipy:      1.14.1  
  OpenGL:     3.1.6  
  Image:      10.4.0 (PIL or Pillow)
  Platform:   darwin 64bit x86_64
  GSAS-II:    5e15c3, 21-Dec-2024 12:32 (1.0 days old). Tag: #5801
```

**Comment by briantoby** [comment]
This is very strange. Is it possible you have more than one copy of GSAS-II installed? You clearly are using an older version of the code in the scriptable. Could you add into your script print(f'Version information:\n{G2sc.ShowVersions()}') [(see docs)](https://gsas-ii.readthedocs.io/en/latest/GSASIIscriptable.html#status-information) to get more info on scriptable?

BTW, your error: 
```Module pyspg in '/Users/longyang/opt/anaconda3/envs/gsas2/GSASII/bindist' could not be loaded``` (etc)
is because you have two sets of GSAS-II binary files, one in directory: /Users/longyang/opt/anaconda3/envs/gsas2/GSASII-bin/mac_64_p3.11_n1.26 (that works with your Python) and one in /Users/longyang/opt/anaconda3/envs/gsas2/GSASII/bindist that does not. Do you have the git and older svn installations somehow intermingled? You can remove the bindist files to get rid of this error, but I am concerned that you even see it.

I did test and the new option works:
```
In [6]: hist1.getdata('x')
Out[6]: array([ 10.   ,  10.025,  10.05 , ..., 159.925, 159.95 , 159.975])

In [7]: hist1.getdata('d')
Out[7]: 
array([8.83762763, 8.8156447 , 8.79377128, ..., 0.78222279, 0.7821926 ,
       0.78216246])

In [8]: hist1.getdata('q')
Out[8]: 
array([0.71095837, 0.71273123, 0.71450406, ..., 8.0324754 , 8.03278539,
       8.033095  ])

In [9]: hist1.getdata('?')
---------------------------------------------------------------------------
G2ScriptException                         Traceback (most recent call last)
Cell In[9], line 1
----> 1 hist1.getdata('?')

File ~/G2/git/g2full/GSAS-II/GSASII/GSASIIscriptable.py:3608, in G2PwdrData.getdata(self, datatype)
   3606 enums = ['x', 'yobs', 'yweight', 'ycalc', 'background', 'residual', 'q', 'd']
   3607 if datatype.lower() not in enums:
-> 3608     raise G2ScriptException("Invalid datatype = "+datatype+" must be one of "+str(enums))
   3609 if datatype.lower() == 'q':
   3610     Inst,Inst2 = self.data['Instrument Parameters']

G2ScriptException: Invalid datatype = ? must be one of ['x', 'yobs', 'yweight', 'ycalc', 'background', 'residual', 'q', 'd']
```

**Comment by dragonyanglong** [comment]
Yes, you are right. The GSASIIscriptable version is old, as follows. Is there any python script code to force it to update?

```
GSAS-II binary directory: /Users/longyang/opt/anaconda3/envs/gsas2/GSASII-bin/mac_64_p3.11_n1.26
7 values read from config file /Users/longyang/opt/anaconda3/envs/gsas2/GSASII/config.py
Version information:
  Python      3.11.10:  from /Users/longyang/opt/anaconda3/envs/gsas2/bin/python
  numpy       1.26.4:
  scipy       1.14.1:
Latest GSAS-II revision: 5796 (svn SVN version 5796)

GSAS-II location: /Users/longyang/opt/anaconda3/envs/gsas2/GSASII
Binary location:  /Users/longyang/opt/anaconda3/envs/gsas2/GSASII-bin/mac_64_p3.11_n1.26
```
